# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('email', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=7)),
                ('address', models.TextField()),
                ('job', models.TextField()),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
